package http_server

import (
	"github.com/gin-gonic/gin"
	v1 "sea-battle/api/rest/v1"

	ginSwagger "github.com/swaggo/gin-swagger"   // gin-swagger middleware
	"github.com/swaggo/gin-swagger/swaggerFiles" // swagger embed files
	_ "sea-battle/docs"                          // docs is generated by Swag CLI, you have to import it.
)

// swaggerRoute - swagger doc route.
var swaggerRoute = func(router *gin.Engine) {
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

// restRoute - v1 rest route.
var restRoute = func(router *gin.Engine) *gin.RouterGroup {
	return router.Group("/rest/v1")
}

// initRouter initializes the HTTP server routing.
func initRouter(router *gin.Engine) {
	swaggerRoute(router)
	v1.GameRoutesGroup(restRoute(router))
}
